version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - "./data:/data/db"
    networks:
      - fp_network

  geo-service:
    build: geo-service
    container_name: geo-service
    ports:
      - "5000:5000"
    volumes:
      - "./geo-service:/app"
    networks:
      - fp_network

  backend-service:
    build:
      context: backend
      args:
        NODE_ENV: dev
    container_name: backend-service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/opt/app"
    depends_on:
      - mongodb
    networks:
      - fp_network

  client:
    build:
      context: client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
    stdin_open: true
    depends_on:
      - mongodb
      - geo-service
      - backend-service
    networks:
      - fp_network

networks:
  fp_network:
    driver: bridge
