version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - fp_network
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - fp_network
    depends_on:
      - mongo

  geo-service:
    build: geo-service
    container_name: geo-service
    ports:
      - "5000:5000"
    volumes:
      - "./geo-service:/app"
    networks:
      - fp_network

  backend-service:
    build:
      context: backend
      args:
        NODE_ENV: dev
    container_name: backend-service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    depends_on:
      - mongo
      - mongo-express
    networks:
      - fp_network

  client:
    build:
      context: client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
    stdin_open: true
    depends_on:
      - mongo
      - geo-service
      - backend-service
    networks:
      - fp_network

networks:
  fp_network:
    driver: bridge
