name: build_images

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        uses: docker/build-push-action@v1.0.1
        with:
          path: ./backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fight-pandemics/backend
          tag_with_ref: true
  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        uses: docker/build-push-action@v1.0.1
        with:
          path: ./client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fight-pandemics/client
          tag_with_ref: true
  build_geo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        uses: docker/build-push-action@v1.0.1
        with:
          path: ./geo-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fight-pandemics/geo-service
          tag_with_ref: true
